/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddShoppingRouteImport } from './routes/add.shopping'
import { Route as AddOutgoingRouteImport } from './routes/add.outgoing'
import { Route as AddIncomeRouteImport } from './routes/add.income'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRecurringRouteImport } from './routes/_app.recurring'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppGoalsRouteImport } from './routes/_app.goals'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as ApiPublicHooksRunRecurringRouteImport } from './routes/api/public/hooks/run-recurring'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddShoppingRoute = AddShoppingRouteImport.update({
  id: '/add/shopping',
  path: '/add/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOutgoingRoute = AddOutgoingRouteImport.update({
  id: '/add/outgoing',
  path: '/add/outgoing',
  getParentRoute: () => rootRouteImport,
} as any)
const AddIncomeRoute = AddIncomeRouteImport.update({
  id: '/add/income',
  path: '/add/income',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksRunRecurringRoute =
  ApiPublicHooksRunRecurringRouteImport.update({
    id: '/api/public/hooks/run-recurring',
    path: '/api/public/hooks/run-recurring',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/insights': typeof AppInsightsRoute
  '/recurring': typeof AppRecurringRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/add/income': typeof AddIncomeRoute
  '/add/outgoing': typeof AddOutgoingRoute
  '/add/shopping': typeof AddShoppingRoute
  '/api/public/hooks/run-recurring': typeof ApiPublicHooksRunRecurringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/goals': typeof AppGoalsRoute
  '/insights': typeof AppInsightsRoute
  '/recurring': typeof AppRecurringRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/add/income': typeof AddIncomeRoute
  '/add/outgoing': typeof AddOutgoingRoute
  '/add/shopping': typeof AddShoppingRoute
  '/api/public/hooks/run-recurring': typeof ApiPublicHooksRunRecurringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/recurring': typeof AppRecurringRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/add/income': typeof AddIncomeRoute
  '/add/outgoing': typeof AddOutgoingRoute
  '/add/shopping': typeof AddShoppingRoute
  '/api/public/hooks/run-recurring': typeof ApiPublicHooksRunRecurringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/recurring'
    | '/settings'
    | '/transactions'
    | '/add/income'
    | '/add/outgoing'
    | '/add/shopping'
    | '/api/public/hooks/run-recurring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/goals'
    | '/insights'
    | '/recurring'
    | '/settings'
    | '/transactions'
    | '/add/income'
    | '/add/outgoing'
    | '/add/shopping'
    | '/api/public/hooks/run-recurring'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/goals'
    | '/_app/insights'
    | '/_app/recurring'
    | '/_app/settings'
    | '/_app/transactions'
    | '/add/income'
    | '/add/outgoing'
    | '/add/shopping'
    | '/api/public/hooks/run-recurring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  AddIncomeRoute: typeof AddIncomeRoute
  AddOutgoingRoute: typeof AddOutgoingRoute
  AddShoppingRoute: typeof AddShoppingRoute
  ApiPublicHooksRunRecurringRoute: typeof ApiPublicHooksRunRecurringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/shopping': {
      id: '/add/shopping'
      path: '/add/shopping'
      fullPath: '/add/shopping'
      preLoaderRoute: typeof AddShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/outgoing': {
      id: '/add/outgoing'
      path: '/add/outgoing'
      fullPath: '/add/outgoing'
      preLoaderRoute: typeof AddOutgoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/income': {
      id: '/add/income'
      path: '/add/income'
      fullPath: '/add/income'
      preLoaderRoute: typeof AddIncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recurring': {
      id: '/_app/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/run-recurring': {
      id: '/api/public/hooks/run-recurring'
      path: '/api/public/hooks/run-recurring'
      fullPath: '/api/public/hooks/run-recurring'
      preLoaderRoute: typeof ApiPublicHooksRunRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  AddIncomeRoute: AddIncomeRoute,
  AddOutgoingRoute: AddOutgoingRoute,
  AddShoppingRoute: AddShoppingRoute,
  ApiPublicHooksRunRecurringRoute: ApiPublicHooksRunRecurringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
